# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# new
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY your_site_crt_file.crt /etc/nginx/certs/your_site_crt_file.crt
COPY your_site_crt_file.key /etc/nginx/certs/your_site_crt_file.key
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]