version: "3.3"
services:
  model_api:
    build: ./model_api
    container_name: "model_api"
    ports:
      - "5000:5000"
  django:
    build: ./covid
    container_name: "django"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/covid/frontend/public/

  react:
    build: ./frontend
    container_name: "react"
    ports:
      - "3000:3000"
    volumes:
      - ./data/pictures:/usr/share/nginx/html/pictures

  db:
    image: mysql:5.7
    container_name: "mysql"
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "med"
      # You can use whatever password you like
      MYSQL_PASSWORD: "med123456789"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "med123456789"
      MYSQL_DATABASE: "pfe"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"

    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
  data01:
    driver: local
