FROM python:3.7
# exposing our stream port in docker internal network
EXPOSE 8000
# creates a dir for our application
WORKDIR /covid
# copy our requirements.txt file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt
# copy the rest of our application
COPY . .
# run the application
RUN python manage.py makemigrations 
RUN python manage.py migrate
CMD python manage.py runserver 0.0.0.0:8000