FROM python:3.7
# exposing our stream port in docker internal network
EXPOSE 5000
# creates a dir for our application
WORKDIR /app
# copy our requirements.txt file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install -U flask-cors
# copy the rest of our application
COPY . .
# run the application

CMD python server.py